
version: '3'
services:
  web:
    build: .
    command: python Rag_persona/manage.py runserver 0.0.0.0:8000
    container_name: api_service
    volumes:
      - .:/api_service
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: