
version: '3'
services:
  web:
    build: .
    command: python Rag_persona/manage.py runserver 0.0.0.0:8000
    container_name: api_service
    volumes:
      - .:/api_service
    ports:
      - "8000:8000"

    env_file:
      - .env
    
    environment:
      - name=${DB_NAME}

    depends_on:
      - db
  db:
    image: postgres:16
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${PASSWORD}

volumes:
  postgres_data: